CREATE TABLE tunnit (
	id SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	work_date DATE NOT NULL,
	start_time VARCHAR(5),
	end_time VARCHAR(5),
	info VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
